// Comprehensive mock data for AI assistant demo
// Replace individual sections with live DB/API queries when integrating

export const mockBuildings = [
  {
    id: 'b1',
    code: 'L127',
    name: 'Lygon 127',
    address: '127 Lygon Street, Carlton VIC 3053',
    suburb: 'Carlton',
    total_units: 48,
    manages_electricity: true,
    manages_maintenance: true,
  },
  {
    id: 'b2',
    code: 'PKV',
    name: 'Parkview Apartments',
    address: '45 Park Drive, Parkville VIC 3052',
    suburb: 'Parkville',
    total_units: 32,
    manages_electricity: true,
    manages_maintenance: true,
  },
  {
    id: 'b3',
    code: 'UG',
    name: 'University Gardens',
    address: '12 Swanston St, Melbourne VIC 3000',
    suburb: 'Melbourne CBD',
    total_units: 60,
    manages_electricity: false,
    manages_maintenance: true,
  },
  {
    id: 'b4',
    code: 'HC',
    name: 'Hawthorn Court',
    address: '88 Glenferrie Rd, Hawthorn VIC 3122',
    suburb: 'Hawthorn',
    total_units: 24,
    manages_electricity: true,
    manages_maintenance: true,
  },
]

export const mockProperties = [
  {
    id: 'p1',
    property_code: 'L127/101',
    unit_number: '101',
    building_id: 'b1',
    building_code: 'L127',
    building_name: 'Lygon 127',
    property_type: 'Studio',
    bedrooms: 0,
    bathrooms: 1,
    floor_level: 1,
    size_sqm: 28,
    rent_amount: 380,
    bond_amount: 760,
    status: 'occupied',
    available_date: null,
    days_vacant: 0,
    owner_name: 'Chen Investment Pty Ltd',
    owner_email: 'accounts@cheninvest.com.au',
  },
  {
    id: 'p2',
    property_code: 'L127/204',
    unit_number: '204',
    building_id: 'b1',
    building_code: 'L127',
    building_name: 'Lygon 127',
    property_type: '1 Bedroom',
    bedrooms: 1,
    bathrooms: 1,
    floor_level: 2,
    size_sqm: 42,
    rent_amount: 450,
    bond_amount: 900,
    status: 'available',
    available_date: '2026-06-01',
    days_vacant: 19,
    owner_name: 'M. Rosenberg',
    owner_email: 'mark.rosenberg@gmail.com',
  },
  {
    id: 'p3',
    property_code: 'L127/312',
    unit_number: '312',
    building_id: 'b1',
    building_code: 'L127',
    building_name: 'Lygon 127',
    property_type: '1 Bedroom',
    bedrooms: 1,
    bathrooms: 1,
    floor_level: 3,
    size_sqm: 44,
    rent_amount: 460,
    bond_amount: 920,
    status: 'maintenance_hold',
    available_date: null,
    days_vacant: 34,
    owner_name: 'Chen Investment Pty Ltd',
    owner_email: 'accounts@cheninvest.com.au',
  },
  {
    id: 'p4',
    property_code: 'PKV/102',
    unit_number: '102',
    building_id: 'b2',
    building_code: 'PKV',
    building_name: 'Parkview Apartments',
    property_type: '1 Bedroom',
    bedrooms: 1,
    bathrooms: 1,
    floor_level: 1,
    size_sqm: 40,
    rent_amount: 430,
    bond_amount: 860,
    status: 'available',
    available_date: '2026-06-10',
    days_vacant: 10,
    owner_name: 'T. Nguyen',
    owner_email: 'tony.nguyen@outlook.com',
  },
  {
    id: 'p5',
    property_code: 'PKV/301',
    unit_number: '301',
    building_id: 'b2',
    building_code: 'PKV',
    building_name: 'Parkview Apartments',
    property_type: '2 Bedroom',
    bedrooms: 2,
    bathrooms: 1,
    floor_level: 3,
    size_sqm: 62,
    rent_amount: 580,
    bond_amount: 1160,
    status: 'occupied',
    available_date: null,
    days_vacant: 0,
    owner_name: 'Parkview Holdings Pty Ltd',
    owner_email: 'admin@parkviewhold.com.au',
  },
  {
    id: 'p6',
    property_code: 'UG/1B',
    unit_number: '1B',
    building_id: 'b3',
    building_code: 'UG',
    building_name: 'University Gardens',
    property_type: 'Studio',
    bedrooms: 0,
    bathrooms: 1,
    floor_level: 1,
    size_sqm: 26,
    rent_amount: 360,
    bond_amount: 720,
    status: 'available',
    available_date: '2026-05-15',
    days_vacant: 36,
    owner_name: 'Swanston Invest Pty Ltd',
    owner_email: 'finance@swanstoninvest.com.au',
  },
  {
    id: 'p7',
    property_code: 'HC/B01',
    unit_number: 'B01',
    building_id: 'b4',
    building_code: 'HC',
    building_name: 'Hawthorn Court',
    property_type: '1 Bedroom',
    bedrooms: 1,
    bathrooms: 1,
    floor_level: 1,
    size_sqm: 38,
    rent_amount: 420,
    bond_amount: 840,
    status: 'on_hold',
    available_date: '2026-07-01',
    days_vacant: 7,
    owner_name: 'E. Blackwood',
    owner_email: 'eliza.blackwood@hotmail.com',
  },
]

export const mockTenants = [
  {
    id: 't1',
    first_name: 'Yuki',
    last_name: 'Tanaka',
    email: 'yuki.tanaka@student.unimelb.edu.au',
    phone: '0412 345 678',
    property_code: 'L127/101',
    property_id: 'p1',
    lease_start: '2026-02-01',
    lease_end: '2027-01-31',
    rent_amount: 380,
    payment_status: 'current',
    electricity_status: 'active',
    electricity_balance_owing: 0,
    enrolment_verified: true,
    university: 'University of Melbourne',
    study_program: 'Master of Engineering',
  },
  {
    id: 't2',
    first_name: 'Ravi',
    last_name: 'Krishnamurthy',
    email: 'ravi.k@student.rmit.edu.au',
    phone: '0423 456 789',
    property_code: 'PKV/301',
    property_id: 'p5',
    lease_start: '2026-01-15',
    lease_end: '2026-12-31',
    rent_amount: 290,
    payment_status: 'overdue',
    electricity_status: 'active',
    electricity_balance_owing: 237.50,
    enrolment_verified: true,
    university: 'RMIT University',
    study_program: 'Bachelor of IT',
    notes: 'Two missed direct debit payments. Failed DDR on 5 Jun and 19 Jun.',
  },
  {
    id: 't3',
    first_name: 'Amara',
    last_name: 'Osei',
    email: 'amara.osei@student.monash.edu',
    phone: '0434 567 890',
    property_code: 'PKV/301',
    property_id: 'p5',
    lease_start: '2026-01-15',
    lease_end: '2026-12-31',
    rent_amount: 290,
    payment_status: 'current',
    electricity_status: 'active',
    electricity_balance_owing: 0,
    enrolment_verified: true,
    university: 'Monash University',
    study_program: 'Doctor of Medicine',
  },
]

export const mockApplications = [
  {
    id: 'a1',
    reference: 'APP-2026-0041',
    applicant_first_name: 'Mei Lin',
    applicant_last_name: 'Chen',
    applicant_email: 'meilin.chen@student.unimelb.edu.au',
    applicant_phone: '0445 123 456',
    property_code: 'PKV/102',
    property_id: 'p4',
    building_name: 'Parkview Apartments',
    preferred_move_in: '2026-07-01',
    status: 'reviewing',
    submitted_at: '2026-06-14',
    agent_name: 'Marcus Webb',
    documents: {
      passport: true,
      proof_of_enrolment: true,
      holding_deposit: true,
      lease_acceptance: false,
    },
    university: 'University of Melbourne',
    study_program: 'Bachelor of Arts',
    notes: 'Awaiting signed lease acceptance. Application otherwise complete.',
  },
  {
    id: 'a2',
    reference: 'APP-2026-0042',
    applicant_first_name: 'Arjun',
    applicant_last_name: 'Patel',
    applicant_email: 'arjun.p@student.rmit.edu.au',
    applicant_phone: '0456 234 567',
    property_code: 'UG/1B',
    property_id: 'p6',
    building_name: 'University Gardens',
    preferred_move_in: '2026-07-01',
    status: 'new',
    submitted_at: '2026-06-18',
    agent_name: null,
    documents: {
      passport: true,
      proof_of_enrolment: false,
      holding_deposit: false,
      lease_acceptance: false,
    },
    university: 'RMIT University',
    study_program: 'Master of Architecture',
    notes: 'Missing proof of enrolment and holding deposit. No agent referred.',
  },
  {
    id: 'a3',
    reference: 'APP-2026-0039',
    applicant_first_name: 'Sophie',
    applicant_last_name: 'Thompson',
    applicant_email: 'sophie.t@student.monash.edu',
    applicant_phone: '0467 345 678',
    property_code: 'HC/B01',
    property_id: 'p7',
    building_name: 'Hawthorn Court',
    preferred_move_in: '2026-07-01',
    status: 'approved',
    submitted_at: '2026-06-10',
    agent_name: 'Lena Kovač',
    documents: {
      passport: true,
      proof_of_enrolment: true,
      holding_deposit: true,
      lease_acceptance: true,
    },
    university: 'Monash University',
    study_program: 'Bachelor of Science',
    notes: 'All documents received. Lease signed. Awaiting move-in confirmation.',
  },
  {
    id: 'a4',
    reference: 'APP-2026-0044',
    applicant_first_name: 'James',
    applicant_last_name: 'O\'Sullivan',
    applicant_email: 'james.os@student.unimelb.edu.au',
    applicant_phone: '0478 456 789',
    property_code: 'L127/204',
    property_id: 'p2',
    building_name: 'Lygon 127',
    preferred_move_in: '2026-07-15',
    status: 'reviewing',
    submitted_at: '2026-06-17',
    agent_name: 'Marcus Webb',
    documents: {
      passport: false,
      proof_of_enrolment: true,
      holding_deposit: true,
      lease_acceptance: false,
    },
    university: 'University of Melbourne',
    study_program: 'Juris Doctor',
    notes: 'Missing passport copy and lease acceptance. Holding deposit received.',
  },
  {
    id: 'a5',
    reference: 'APP-2026-0043',
    applicant_first_name: 'Fatima',
    applicant_last_name: 'Al-Rashidi',
    applicant_email: 'fatima.ar@student.deakin.edu.au',
    applicant_phone: '0489 567 890',
    property_code: 'L127/204',
    property_id: 'p2',
    building_name: 'Lygon 127',
    preferred_move_in: '2026-07-01',
    status: 'reviewing',
    submitted_at: '2026-06-16',
    agent_name: null,
    documents: {
      passport: true,
      proof_of_enrolment: true,
      holding_deposit: false,
      lease_acceptance: false,
    },
    university: 'Deakin University',
    study_program: 'Master of Nursing',
    notes: 'Missing holding deposit and lease acceptance.',
  },
]

export const mockMaintenanceJobs = [
  {
    id: 'm1',
    job_number: 'MNT-2026-0118',
    title: 'Hot water system not working',
    property_code: 'L127/312',
    property_id: 'p3',
    building_name: 'Lygon 127',
    category: 'Plumbing',
    priority: 'urgent',
    status: 'in_progress',
    reported_by: 'Manager inspection',
    assigned_to: 'Dave Plumbing Pty Ltd',
    created_at: '2026-06-10',
    due_date: '2026-06-13',
    completed_at: null,
    estimated_cost: 800,
    actual_cost: null,
    is_blocking_leasing: true,
    notes: 'Hot water system failed. Unit is on maintenance hold. Plumber attended 12 Jun but needs replacement part (ETA 23 Jun).',
  },
  {
    id: 'm2',
    job_number: 'MNT-2026-0122',
    title: 'Mould in bathroom',
    property_code: 'L127/101',
    property_id: 'p1',
    building_name: 'Lygon 127',
    category: 'Cleaning / Hygiene',
    priority: 'high',
    status: 'assigned',
    reported_by: 'Tenant (Yuki Tanaka)',
    assigned_to: 'Metro Maintenance Team',
    created_at: '2026-06-15',
    due_date: '2026-06-22',
    completed_at: null,
    estimated_cost: 200,
    actual_cost: null,
    is_blocking_leasing: false,
    notes: 'Tenant reported mould in bathroom ceiling. Scheduled remediation for 21 Jun.',
  },
  {
    id: 'm3',
    job_number: 'MNT-2026-0115',
    title: 'Broken window latch – Unit 204',
    property_code: 'L127/204',
    property_id: 'p2',
    building_name: 'Lygon 127',
    category: 'Building / Structure',
    priority: 'medium',
    status: 'new',
    reported_by: 'Manager inspection',
    assigned_to: null,
    created_at: '2026-06-12',
    due_date: '2026-06-26',
    completed_at: null,
    estimated_cost: 120,
    actual_cost: null,
    is_blocking_leasing: false,
    notes: 'Window latch in bedroom is broken. Unit is available but this should be fixed before move-in.',
  },
  {
    id: 'm4',
    job_number: 'MNT-2026-0109',
    title: 'Air conditioning unit fault',
    property_code: 'PKV/301',
    property_id: 'p5',
    building_name: 'Parkview Apartments',
    category: 'HVAC',
    priority: 'medium',
    status: 'waiting_parts',
    reported_by: 'Tenant (Ravi Krishnamurthy)',
    assigned_to: 'CoolAir Services',
    created_at: '2026-06-05',
    due_date: '2026-06-25',
    completed_at: null,
    estimated_cost: 450,
    actual_cost: null,
    is_blocking_leasing: false,
    notes: 'Split system not cooling. Technician attended 8 Jun. Awaiting replacement compressor unit.',
  },
  {
    id: 'm5',
    job_number: 'MNT-2026-0098',
    title: 'Carpet replacement',
    property_code: 'UG/1B',
    property_id: 'p6',
    building_name: 'University Gardens',
    category: 'Flooring',
    priority: 'medium',
    status: 'waiting_quote',
    reported_by: 'Manager inspection',
    assigned_to: null,
    created_at: '2026-05-28',
    due_date: '2026-06-21',
    completed_at: null,
    estimated_cost: null,
    actual_cost: null,
    is_blocking_leasing: true,
    notes: 'Carpet stained beyond repair after previous tenant. Unit available but carpet must be replaced before new tenant. Two quotes requested, none received.',
  },
  {
    id: 'm6',
    job_number: 'MNT-2026-0119',
    title: 'Intercom not functioning – Building entry',
    property_code: null,
    property_id: null,
    building_name: 'Parkview Apartments',
    category: 'Security / Access',
    priority: 'high',
    status: 'assigned',
    reported_by: 'Manager',
    assigned_to: 'SecureTech Solutions',
    created_at: '2026-06-14',
    due_date: '2026-06-21',
    completed_at: null,
    estimated_cost: 350,
    actual_cost: null,
    is_blocking_leasing: false,
    notes: 'Front door intercom panel failed. Technician booked for 20 Jun.',
  },
]

export const mockElectricityAccounts = [
  {
    id: 'e1',
    property_code: 'L127/101',
    property_id: 'p1',
    tenant_name: 'Yuki Tanaka',
    tenant_email: 'yuki.tanaka@student.unimelb.edu.au',
    building_name: 'Lygon 127',
    status: 'active',
    meter_id: 'LG127-101-M',
    latest_read_kwh: 142.3,
    latest_read_date: '2026-06-15',
    current_balance_owing: 0,
    last_invoice_amount: 87.40,
    last_invoice_date: '2026-06-01',
    last_payment_date: '2026-06-07',
    payment_method: 'direct_debit',
    ddr_status: 'active',
    notes: 'Account in good standing.',
  },
  {
    id: 'e2',
    property_code: 'PKV/301',
    property_id: 'p5',
    tenant_name: 'Ravi Krishnamurthy & Amara Osei',
    tenant_email: 'ravi.k@student.rmit.edu.au',
    building_name: 'Parkview Apartments',
    status: 'active',
    meter_id: 'PKV-301-M',
    latest_read_kwh: 289.7,
    latest_read_date: '2026-06-15',
    current_balance_owing: 237.50,
    last_invoice_amount: 124.60,
    last_invoice_date: '2026-06-01',
    last_payment_date: '2026-05-05',
    payment_method: 'direct_debit',
    ddr_status: 'failed',
    ddr_failure_reason: 'Insufficient funds – 2 consecutive failures (5 Jun, 19 Jun)',
    notes: 'Two consecutive DDR failures. Manual follow-up required. Suspending service after 30 Jun if unpaid.',
  },
  {
    id: 'e3',
    property_code: 'L127/204',
    property_id: 'p2',
    tenant_name: 'Vacant',
    tenant_email: null,
    building_name: 'Lygon 127',
    status: 'pending_setup',
    meter_id: 'LG127-204-M',
    latest_read_kwh: 0,
    latest_read_date: null,
    current_balance_owing: 0,
    last_invoice_amount: null,
    last_invoice_date: null,
    last_payment_date: null,
    payment_method: null,
    ddr_status: null,
    notes: 'Unit vacant. Electricity account will be set up on new tenant move-in.',
  },
  {
    id: 'e4',
    property_code: 'HC/B01',
    property_id: 'p7',
    tenant_name: 'Pending – Sophie Thompson',
    tenant_email: 'sophie.t@student.monash.edu',
    building_name: 'Hawthorn Court',
    status: 'pending_consent',
    meter_id: 'HC-B01-M',
    latest_read_kwh: 0,
    latest_read_date: null,
    current_balance_owing: 0,
    last_invoice_amount: null,
    last_invoice_date: null,
    last_payment_date: null,
    payment_method: null,
    ddr_status: null,
    notes: 'Awaiting DDR consent form from incoming tenant Sophie Thompson.',
  },
]

export const mockAgents = [
  {
    id: 'ag1',
    name: 'Marcus Webb',
    agency: 'Webb Student Lettings',
    email: 'marcus@webbstudent.com.au',
    phone: '0411 222 333',
    applications_this_month: 3,
    commission_rate: 0.5,
  },
  {
    id: 'ag2',
    name: 'Lena Kovač',
    agency: 'City Campus Rentals',
    email: 'lena@citycampus.com.au',
    phone: '0422 333 444',
    applications_this_month: 1,
    commission_rate: 0.5,
  },
]
